name: SyncSpace-CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: 9.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c release

      - name: Publish
        run: dotnet publish ./src/SyncSpace.API/SyncSpace.API.csproj -o ./api --no-build -p:DeployOnBuild=true -p:WebPublishMethod=Package

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: api-artifact
          path: ./api

  deploy-prod:
    environment: 
      name: 'Production'
      url: 'https://syncspace.runasp.net'
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: api-artifact
          path: ./api

      # Install MSDeploy
      - name: Install MSDeploy
        run: |
          curl -o msdeploy.zip https://download.microsoft.com/download/1/F/4/1F4CCEC5-5E7C-4743-8BE8-44E29DD94B98/WebDeploy_amd64_en-US.msi
          msiexec /i msdeploy.zip /quiet /qn /norestart

      - name: Deploy to monsterasp
        run: |
          msdeploy.exe -verb:sync -source:package=./api -dest:publishSettings=${{ secrets.PUBLISH_PROFILE }}
