name: SyncSpace-CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: 9.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c release

      - name: Publish
        run: dotnet publish ./src/SyncSpace.API/SyncSpace.API.csproj -o ./api --no-build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: api-artifact
          path: ./api

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: api-artifact
          path: ./api

      - name: Deploy to Monster ASP .NET via FTP/SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./api
          server-dir: wwwroot/
          protocol: ftp
